tickers:
- A
- AAPL
- ABBV
- ADI
- ADM
- AEE
- AEP
- AES
- ALB
- ALLE
- AMAT
- AME
- AMGN
- AOS
- APA
- APH
- APTV
- ATO
- AVGO
- AVY
- AWK
- BALL
- BAX
- BBY
- BDX
- BF-B
- BG
- BKR
- BMY
- CAG
- CAH
- CAT
- CDW
- CEG
- CHD
- CL
- CLX
- CMI
- CMS
- CNP
- COO
- COP
- COST
- CPB
- CSCO
- CSX
- CTAS
- CTRA
- CTVA
- CVS
- CVX
- DD
- DE
- DELL
- DG
- DGX
- DHR
- DIS
- DOV
- DOW
- DPZ
- DRI
- DTE
- DUK
- DVN
- ECL
- EIX
- EL
- EME
- EMR
- ES
- ETN
- EVRG
- EXC
- F
- FANG
- FAST
- FCX
- FDX
- FE
- FOX
- FOXA
- FTV
- GD
- GE
- GEHC
- GILD
- GLW
- GM
- GPC
- GWW
- HAL
- HAS
- HCA
- HD
- HII
- HON
- HPQ
- HRL
- HSY
- HUBB
- HWM
- IBM
- IEX
- IFF
- INTC
- IP
- IR
- ITW
- JCI
- JNJ
- K
- KDP
- KHC
- KLAC
- KMB
- KO
- KVUE
- LDOS
- LH
- LHX
- LII
- LIN
- LKQ
- LLY
- LMT
- LNT
- LRCX
- LW
- LYB
- MAS
- MCD
- MCHP
- MCK
- MDLZ
- MDT
- MGM
- MKC
- MLM
- MMM
- MO
- MOS
- MPC
- MRK
- MSFT
- MSI
- MU
- NDSN
- NEE
- NI
- NOC
- NRG
- NSC
- NTAP
- NUE
- NVDA
- NWS
- NWSA
- NXPI
- O
- OKE
- OMC
- OXY
- PAYC
- PCG
- PEG
- PEP
- PFE
- PG
- PH
- PHM
- PKG
- PM
- PNR
- PNW
- POOL
- PPG
- PPL
- PSKY
- PSX
- PWR
- RL
- RMD
- ROL
- ROP
- ROST
- RSG
- RTX
- RVTY
- SHW
- SJM
- SLB
- SNA
- SO
- SRE
- STE
- STLD
- STX
- STZ
- SWK
- SYY
- T
- TAP
- TECH
- TEL
- TER
- TGT
- TJX
- TMO
- TRGP
- TSN
- TT
- TXN
- TXT
- UHS
- UNP
- UPS
- VLO
- VLTO
- VMC
- VST
- VTRS
- VZ
- WAB
- WEC
- WM
- WMB
- WMT
- WST
- XEL
- XYL
- ZBH
- ZTS
macro_tickers:
- ^TNX
- ^IRX
- ^GSPC
frequency: quarterly
start_year: 1990
end_year: 2025
paths:
  raw_dir: data/raw
  proc_dir: data/processed
  results_dir: results
training:
  horizon: 1
  window: 3
  batch_size: 16
  epochs: 1000
  learning_rate: 1e-3
  weight_identity: 5.0
  weight_growth: 1.0
  weight_level: 0.3
  rolling_mean_window: 4
  splits:
    train_end_year: 2015
    val_end_year: 2019
    train_frac: 0.6
    val_frac: 0.2
  val_split: 0.2
  hidden_dim: 8
